### ISSUE TITLE
代码排版问题

### ISSUE THREAD

**Issue by lvxianchao** [zsy78191/Rework-Reader#2]
如图，**关闭阅读原文**后代码块会被挤成一行，没有排版。

![image](https://user-images.githubusercontent.com/22412818/56880518-b6b9ac80-6a8f-11e9-82ae-3f561b0382a3.png)

**Comment by zsy78191** [comment]
麻烦提供一下源

**Comment by lvxianchao** [comment]
@zsy78191 廖雪峰的网站就可以看到

**Comment by zsy78191** [comment]
好的，谢谢

**Comment by 9yearfish** [comment]
哈哈，这好的项目，才这么点人start。不科学啊。

**Comment by lvxianchao** [comment]
@aoxiang594 RSS 订阅这个东西，要做起各种端才好，桌面、浏览器插件、移动端，目前这个项目好像只有移动端。

**Comment by 9yearfish** [comment]
是啊，刚刚也想问有没有mac客户端或者啥的。试了几个APP，感觉这个最棒了

**Comment by zsy78191** [comment]
Mac OS 15 出了以后，直接把iPad版本移植到Mac。
