### ISSUE TITLE
首屏的加载中状态图标不消失

### ISSUE THREAD

**Issue by lvxianchao** [zsy78191/Rework-Reader#3]
如图，操作流程如下可以复现这个问题：

随便进行一个订阅源，然后左滑退出到首屏，可见到加载中的图标不消失。

![image](https://user-images.githubusercontent.com/22412818/56880684-4b240f00-6a90-11e9-9ced-a1fc911ef118.png)

另外界面真的很漂亮，合我谓口，一见钟情的那种 👍

**Comment by zsy78191** [comment]
1.1.5修复
