### ISSUE TITLE
功能反馈

### ISSUE THREAD

**Issue by howei6** [zsy78191/Rework-Reader#4]
app非常nice。因为用的ios13 beta版，在appstore无法评论反馈，所以来这里。提两个建议，望斟酌：1. 目前，主界面上部被收藏、稍后阅读，未读等占据，导致rss列表界面比较小，下部也有tab。故实际阅读的部分并不大，希望能提高利用率。2.希望加入超期未读的项自动删除的设置选项

**Comment by howei6** [comment]
再加上设备间同步阅读进步就更好

**Comment by zsy78191** [comment]
同步阅读暂时不做。
UI上面的问题，源码都给你了，对吧。
